# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build rabbit-mq-exp`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t rabbit-mq-exp`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system rabbit-mq-exp && \
          adduser --system -G rabbit-mq-exp rabbit-mq-exp

COPY dist/rabbit-mq-exp rabbit-mq-exp
RUN chown -R rabbit-mq-exp:rabbit-mq-exp .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix rabbit-mq-exp --omit=dev -f install

CMD [ "node", "rabbit-mq-exp" ]
